// Generates supabase/seed.sql from lib/seed-data.js
// Usage: npm run seed:generate
import { writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import * as seed from '../lib/seed-data.js';

export function seedId(key) {
  const h = createHash('md5').update(`leonida-records:${key}`).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => `${q(JSON.stringify(v ?? {}))}::jsonb`;
const arr = (a) => (a && a.length ? `array[${a.map(q).join(',')}]::text[]` : `'{}'::text[]`);

const out = [];
out.push('-- Leonida Records — initial content. Generated by scripts/generate-seed.mjs. Run AFTER schema.sql.');
out.push('-- Safe to re-run: rows are upserted by id / slug.');
out.push('begin;');

out.push('\n-- Sources');
for (const s of seed.sources) {
  out.push(`insert into public.sources (id, name, publisher, kind, url, published_at) values (${q(seedId(s.key))}, ${q(s.name)}, ${q(s.publisher)}, ${q(s.kind)}, ${q(s.url)}, ${q(s.published_at)})
on conflict (id) do update set name = excluded.name, publisher = excluded.publisher, kind = excluded.kind, url = excluded.url, published_at = excluded.published_at;`);
}

out.push('\n-- Entities');
seed.entities.forEach((e, i) => {
  const meta = { ...(e.map ? { map: e.map } : {}), ...(seed.releaseDates[e.key] ? { release_date: seed.releaseDates[e.key] } : {}) };
  out.push(`insert into public.entities (id, type, slug, status, title, eyebrow, short_description, description, quote, hero_image, hero_alt, video_url, tags, primary_source_id, published, featured, sort_order, metadata)
values (${q(seedId(e.key))}, ${q(e.type)}, ${q(e.slug)}, ${q(e.status)}, ${j(e.title)}, ${j(e.eyebrow)}, ${j(e.short)}, ${j(e.desc)}, ${j(e.quote)}, ${q(e.image)}, ${q(e.image ? (e.title.en || e.title.es) : null)}, ${q(e.video_url || null)}, ${arr(e.tags)}, ${q(seedId(e.source))}, true, ${e.featured ? 'true' : 'false'}, ${i}, ${j(meta)})
on conflict (type, slug) do update set status = excluded.status, title = excluded.title, eyebrow = excluded.eyebrow, short_description = excluded.short_description, description = excluded.description, quote = excluded.quote, hero_image = excluded.hero_image, hero_alt = excluded.hero_alt, video_url = excluded.video_url, tags = excluded.tags, primary_source_id = excluded.primary_source_id, featured = excluded.featured, metadata = excluded.metadata;`);
});

out.push('\n-- Facts');
seed.facts.forEach((f, i) => {
  out.push(`insert into public.facts (id, entity_id, title, body, status, source_id, sort_order)
select ${q(seedId(`fact-${i}`))}, e.id, ${j(f.title)}, ${j(f.body)}, ${q(f.status)}, ${q(seedId(f.source))}, ${i}
from public.entities e where e.id = ${q(seedId(f.entity))}
on conflict (id) do update set title = excluded.title, body = excluded.body, status = excluded.status, source_id = excluded.source_id;`);
});

out.push('\n-- Relations');
for (const r of seed.relations) {
  out.push(`insert into public.relations (from_entity_id, to_entity_id, relation_type) values (${q(seedId(r.from))}, ${q(seedId(r.to))}, ${q(r.type)}) on conflict do nothing;`);
}

out.push('\n-- Media library (external official imagery, referenced by URL)');
seed.media.forEach((m, i) => {
  out.push(`insert into public.media (id, url, kind, mime_type, alt_text, caption, credit) values (${q(seedId(m.key))}, ${q(m.url)}, 'image', 'image/jpeg', ${q(m.alt)}, ${q(m.caption)}, ${q(m.credit)})
on conflict (id) do update set url = excluded.url, alt_text = excluded.alt_text, caption = excluded.caption, credit = excluded.credit;`);
  if (m.entity) out.push(`insert into public.entity_media (entity_id, media_id, sort_order) values (${q(seedId(m.entity))}, ${q(seedId(m.key))}, ${i}) on conflict do nothing;`);
});

out.push('\n-- News categories');
seed.categories.forEach((c, i) => {
  out.push(`insert into public.categories (id, slug, name, color, sort_order) values (${q(seedId(c.key))}, ${q(c.slug)}, ${j(c.name)}, ${q(c.color)}, ${i})
on conflict (slug) do update set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order;`);
});

out.push('\n-- The Leonida Times');
for (const a of seed.articles) {
  out.push(`insert into public.articles (id, slug, title, excerpt, body, category_id, tags, cover_image, cover_alt, cover_caption, author_name, source_id, evidence, published, published_at, featured)
values (${q(seedId(a.key))}, ${q(a.slug)}, ${j(a.title)}, ${j(a.excerpt)}, ${j(a.body)}, (select id from public.categories where slug = ${q(seed.categories.find((c) => c.key === a.category)?.slug)}), ${arr(a.tags)}, ${q(a.image)}, ${q(a.title.es)}, ${q(a.cover_caption)}, ${q(a.author)}, ${q(seedId(a.source))}, ${q(a.evidence)}, true, ${q(a.published_at)}, ${a.featured ? 'true' : 'false'})
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, category_id = excluded.category_id, tags = excluded.tags, cover_image = excluded.cover_image, cover_caption = excluded.cover_caption, author_name = excluded.author_name, source_id = excluded.source_id, evidence = excluded.evidence, featured = excluded.featured, published_at = excluded.published_at;`);
  for (const ek of a.entities || []) {
    out.push(`insert into public.article_entities (article_id, entity_id) select a.id, ${q(seedId(ek))} from public.articles a where a.slug = ${q(a.slug)} on conflict do nothing;`);
  }
}

out.push('\n-- Timeline');
seed.timeline.forEach((t, i) => {
  const entity = t.entity ? q(seedId(t.entity)) : 'null';
  const article = t.article ? `(select id from public.articles where slug = ${q(seed.articles.find((a) => a.key === t.article)?.slug)})` : 'null';
  out.push(`insert into public.timeline_events (id, event_date, title, detail, kind, entity_id, article_id, published) values (${q(seedId(`tl-${i}`))}, ${q(t.date)}, ${j(t.title)}, ${j(t.detail)}, ${q(t.kind)}, ${entity}, ${article}, true)
on conflict (id) do update set event_date = excluded.event_date, title = excluded.title, detail = excluded.detail, kind = excluded.kind, entity_id = excluded.entity_id, article_id = excluded.article_id;`);
});

out.push('\n-- Settings');
for (const [k, v] of Object.entries(seed.settings)) {
  out.push(`insert into public.site_settings (key, value) values (${q(k)}, ${q(JSON.stringify(v))}::jsonb) on conflict (key) do update set value = excluded.value where public.site_settings.value = 'null'::jsonb;`);
}

out.push('\ncommit;');
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n') + '\n');
console.log('supabase/seed.sql written');

// ---------------------------------------------------------------------------------------------
// supabase/update-2.5.sql — for sites installed before v2.5 (English as main language + vehicles).
// Safe to run on a live database: it never overwrites content you created or edited.
// ---------------------------------------------------------------------------------------------
const schema = (await import('node:fs')).readFileSync(new URL('../supabase/schema.sql', import.meta.url), 'utf8');
const block = (startMarker) => {
  const i = schema.indexOf(startMarker);
  if (i < 0) throw new Error(`schema block not found: ${startMarker}`);
  const end = schema.indexOf('$$;', i);
  return schema.slice(i, end + 3);
};
const up = [];
up.push(`-- Leonida Records — update to v2.5
-- English becomes the main language (Spanish second; Portuguese and French removed from the site)
-- and the vehicle catalogue is added. Run once in Supabase → SQL Editor. Safe to run more than once.
begin;

-- 1. Localized values fall back to English first, then Spanish
${block('create or replace function public.lr_pick(')}

-- 2. Titles/names may be written in English or Spanish (before: Spanish was mandatory)
do $$
declare r record;
begin
  for r in
    select conrelid::regclass as tbl, conname from pg_constraint
    where contype = 'c'
      and conrelid in ('public.entities'::regclass, 'public.facts'::regclass, 'public.categories'::regclass, 'public.articles'::regclass, 'public.timeline_events'::regclass)
      and pg_get_constraintdef(oid) like '%->> ''es''%'
  loop
    execute format('alter table %s drop constraint %I', r.tbl, r.conname);
  end loop;
end $$;
alter table public.entities        add constraint entities_title_check        check (public.lr_is_localized(title) and (length(coalesce(title ->> 'en', '')) > 0 or length(coalesce(title ->> 'es', '')) > 0));
alter table public.facts           add constraint facts_title_check           check (public.lr_is_localized(title) and (length(coalesce(title ->> 'en', '')) > 0 or length(coalesce(title ->> 'es', '')) > 0));
alter table public.categories      add constraint categories_name_check       check (public.lr_is_localized(name) and (length(coalesce(name ->> 'en', '')) > 0 or length(coalesce(name ->> 'es', '')) > 0));
alter table public.articles        add constraint articles_title_check        check (public.lr_is_localized(title) and (length(coalesce(title ->> 'en', '')) > 0 or length(coalesce(title ->> 'es', '')) > 0));
alter table public.timeline_events add constraint timeline_events_title_check check (public.lr_is_localized(title) and (length(coalesce(title ->> 'en', '')) > 0 or length(coalesce(title ->> 'es', '')) > 0));

-- 3. Activity log labels prefer English
${block('create or replace function public.log_activity()')}

-- 4. Search defaults to English
drop function if exists public.search_archive(text, text, integer);
${block('create or replace function public.search_archive(')}
grant execute on function public.search_archive(text, text, integer) to anon, authenticated;

-- 5. Correct name of the Ultimate Edition buggy (it was listed as "Dominator FX")
update public.entities
set slug = '67-vapid-dominator-buggy',
    title = '{"en": "’67 Vapid Dominator Buggy"}'::jsonb,
    short_description = short_description || ${j(seed.entities.find((e) => e.key === 'veh-vapid-dominator-fx').short)},
    description = description || ${j(seed.entities.find((e) => e.key === 'veh-vapid-dominator-fx').desc)}
where type = 'vehicles' and slug = '67-vapid-dominator-fx';

-- 6. New sources`);
for (const s of seed.sources.filter((x) => ['src-store-ultimate', 'src-gtaintel', 'src-editions', 'src-extended-look', 'src-videos', 'src-screens', 'src-gta6'].includes(x.key))) {
  up.push(`insert into public.sources (id, name, publisher, kind, url, published_at) values (${q(seedId(s.key))}, ${q(s.name)}, ${q(s.publisher)}, ${q(s.kind)}, ${q(s.url)}, ${q(s.published_at)}) on conflict (id) do nothing;`);
}
up.push('\n-- 7. Vehicle catalogue (only adds vehicles that do not exist yet)');
seed.entities.filter((e) => e.key.startsWith('veh-cat-')).forEach((e, i) => {
  up.push(`insert into public.entities (id, type, slug, status, title, eyebrow, short_description, description, quote, hero_image, hero_alt, tags, primary_source_id, published, featured, sort_order, metadata)
values (${q(seedId(e.key))}, 'vehicles', ${q(e.slug)}, ${q(e.status)}, ${j(e.title)}, ${j(e.eyebrow)}, ${j(e.short)}, ${j(e.desc)}, '{}'::jsonb, ${q(e.image)}, ${q(e.image ? e.title.en : null)}, ${arr(e.tags)}, (select id from public.sources where id = ${q(seedId(e.source))}), true, false, ${100 + i}, '{}'::jsonb)
on conflict do nothing;`);
});
up.push('\n-- 8. Official Rockstar photos for vehicles that do not have one yet');
for (const e of seed.entities.filter((x) => x.type === 'vehicles' && x.image)) {
  up.push(`update public.entities set hero_image = ${q(e.image)}, hero_alt = ${q(e.title.en || e.title.es)} where type = 'vehicles' and slug = ${q(e.slug)} and hero_image is null;`);
}
up.push('\ncommit;');
writeFileSync(new URL('../supabase/update-2.5.sql', import.meta.url), up.join('\n') + '\n');
console.log('supabase/update-2.5.sql written');
